USE Logistics;


-- VALIDATING DATA --
SELECT * FROM SHIPMENTS;
SELECT * FROM CUSTOMERS;
SELECT * FROM VEHICLES;
SELECT * FROM WAREHOUSE;
SELECT * FROM ROUTE;
SELECT * FROM CARRIER;

-- CHECK TABLE STRUCTURE --
EXEC sp_help 'SHIPMENTS';
EXEC sp_help 'CUSTOMERS';
EXEC sp_help 'VEHICLES';
EXEC sp_help 'WAREHOUSE';
EXEC sp_help 'ROUTE';
EXEC sp_help 'CARRIER';

-- COUNTING TOTAL ROWS --
SELECT COUNT(*) AS TOTAL_ROWS FROM SHIPMENTS;
SELECT COUNT(*) AS TOTAL_ROWS FROM CUSTOMERS;
SELECT COUNT(*) AS TOTAL_ROWS FROM VEHICLES;
SELECT COUNT(*) AS TOTAL_ROWS FROM WAREHOUSE;
SELECT COUNT(*) AS TOTAL_ROWS FROM ROUTE;
SELECT COUNT(*) AS TOTAL_ROWS FROM CARRIER;

-- CHECKING THE DISTICT TYPES --
SELECT DISTINCT DELIVERY_STATUS FROM SHIPMENTS;
SELECT DISTINCT Customer_Type FROM CUSTOMERS;
SELECT DISTINCT VEHICLE_TYPE FROM VEHICLES;
SELECT DISTINCT MODEL FROM VEHICLES;
SELECT DISTINCT WAREHOUSE_TYPE FROM WAREHOUSE;
SELECT DISTINCT Risk_Level FROM ROUTE;
SELECT DISTINCT Avg_Transit_Days FROM ROUTE ORDER BY Avg_Transit_Days ASC;
SELECT DISTINCT CARRIER_NAME FROM CARRIER ORDER BY Carrier_Name ASC;

-- ADD FORIEGN KEYS --
ALTER TABLE SHIPMENTS
ADD CONSTRAINT FK_SHIPMENTS_CUSTOMERS
FOREIGN KEY (Customer_ID)
REFERENCES CUSTOMERS(Customer_ID);

ALTER TABLE SHIPMENTS
ADD CONSTRAINT FK_SHIPMENTS_VEHICLES
FOREIGN KEY (Vehicle_ID)
REFERENCES VEHICLES(Vehicle_ID);

ALTER TABLE SHIPMENTS
ADD CONSTRAINT FK_SHIPMENTS_WAREHOUSE
FOREIGN KEY (Warehouse_ID)
REFERENCES WAREHOUSE(Warehouse_ID);

ALTER TABLE SHIPMENTS
ADD CONSTRAINT FK_SHIPMENTS_ROUTE
FOREIGN KEY (Route_ID)
REFERENCES ROUTE(Route_ID);

ALTER TABLE SHIPMENTS
ADD CONSTRAINT FK_SHIPMENTS_CARRIERS
FOREIGN KEY (Carrier_ID)
REFERENCES CARRIERS(Carrier_ID);


-- INDEX CREATION FOR BETTER RESULTS --
CREATE INDEX IX_SHIPMENTS ON SHIPMENTS(Shipment_ID);
CREATE INDEX IX_SHIPMENTS_CUSTOMER ON SHIPMENTS(Customer_ID);
CREATE INDEX IX_SHIPMENTS_VEHICLE ON SHIPMENTS(Vehicle_ID);
CREATE INDEX IX_SHIPMENTS_WAREHOUSE ON SHIPMENTS(Warehouse_ID);
CREATE INDEX IX_SHIPMENTS_ROUTE ON SHIPMENTS(Route_ID);
CREATE INDEX IX_SHIPMENTS_CARRIER ON SHIPMENTS(Carrier_ID);



-- ANALYSIS--




--SHIPMENT--
SELECT * FROM SHIPMENTS;


--TOTAL SHIPMENTS--
CREATE VIEW TOTAL_SHIPMENT AS
SELECT COUNT(*) AS TOTAL_SHIPMENTS FROM SHIPMENTS; --6800--
SELECT * FROM TOTAL_SHIPMENT;

--DELIVERED SHIPMENTS--
CREATE VIEW TOTAL_DELIVERED_SHIPMENT AS
SELECT COUNT(*) AS DELIVERED_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'DELIVERED'; --827--
SELECT * FROM TOTAL_DELIVERED_SHIPMENT;

--IN TRASIT SHIPMENTS--
CREATE VIEW INTRANSIT_SHIPMENT AS
SELECT COUNT(*) AS INTRANSIT_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'IN TRANSIT'; --889--
SELECT * FROM INTRANSIT_SHIPMENT;

--DELAYED SHIPMENTS --
CREATE VIEW DELEYED_SHIPMENTS AS
SELECT COUNT(*) AS DELAYED_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'DELAYED'; --893--
SELECT * FROM DELEYED_SHIPMENTS;

--CANCELLED SHIPMENTS--
CREATE VIEW CANCELLED_SHIPMENTS AS
SELECT COUNT(*) AS CANCELLED_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'CANCELLED'; --857--
SELECT * FROM CANCELLED_SHIPMENTS;

--PENDING SHIPMENTS--
CREATE VIEW PENDING_SHIPMENT AS
SELECT COUNT(*) AS PENDING_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'OUT FOR DELIVERY' OR Delivery_Status = 'LOST'; --1700--
SELECT * FROM PENDING_SHIPMENT;

--RETURNED SHIPMENTS--
CREATE VIEW RETURNED_SHIPMENTS AS
SELECT COUNT(*) AS RETURN_SHIPMENTS FROM SHIPMENTS WHERE Delivery_Status = 'RETURN' OR Delivery_Status = 'PICKUP'; --831--
 SELECT * FROM RETURNED_SHIPMENTS;

--AVERAGE DELIVERY DAYS --
CREATE VIEW AVERAGE_DELIVERY_DAYS AS
SELECT AVG(DATEDIFF(DAY, Dispatch_Date, Actual_Delivery)) 
AS Avg_Delivery_Days FROM SHIPMENTS WHERE Actual_Delivery IS NOT NULL; --6--
SELECT * FROM AVERAGE_DELIVERY_DAYS;

--MAXIMUM DELIVERY DAYS --
CREATE VIEW MAX_DELIVERY_DAYS AS
SELECT MAX(DATEDIFF(DAY, Dispatch_Date, Actual_Delivery))
AS Max_Delivery_Days FROM SHIPMENTS WHERE Actual_Delivery IS NOT NULL; --18--
SELECT * FROM MAX_DELIVERY_DAYS;

-- AVERAGE SHIPMENT WEIGHT --
CREATE VIEW AVERAGE_WEIGHT AS
SELECT AVG(Weight_kg) AS Avg_Weight FROM SHIPMENTS; -- 248.21 --
SELECT * FROM AVERAGE_WEIGHT;

--MAXIMUM SHIPMENT WEIGHT --
CREATE VIEW MAX_SHIPMENT_WEIGHT AS
SELECT MAX(Weight_kg) AS Max_Weight FROM SHIPMENTS; --499.91--
SELECT * FROM MAX_SHIPMENT_WEIGHT;

--MINIMUM SHIPMENT WEIGHT --
SELECT MIN(Weight_kg) AS Min_Weight FROM SHIPMENTS; --0.12999--

-- TOTAL FREIGHT CHARGES COLLECTED --
CREATE VIEW TOTAL_FREIGHT_CHARGES AS
SELECT SUM(Freight_Charge_INR) AS Total_Freight FROM SHIPMENTS; --18858409.01--
SELECT * FROM TOTAL_FREIGHT_CHARGES;

-- TOTAL GST COLLECTED --
CREATE VIEW TOTAL_GST AS
SELECT SUM(GST_INR) AS Total_Freight FROM SHIPMENTS; --3501349.69--
SELECT * FROM TOTAL_GST

-- TOP 10 HEAVIEST SHIPMENTS --
SELECT TOP 10 Shipment_ID, Weight_kg FROM SHIPMENTS ORDER BY Weight_kg DESC;

-- TOP 10 SHIPMENTS WHICH HAVE HIGHEST FRIEGHT CHARGES --
SELECT TOP 10 Shipment_ID, Freight_Charge_INR FROM SHIPMENTS 
ORDER BY Freight_Charge_INR DESC;

-- HIGHEST GST --  
SELECT TOP 1 Shipment_ID, GST_INR FROM SHIPMENTS 
ORDER BY GST_INR DESC;   --1599.75--

--LOWEST GST --
SELECT TOP 1 Shipment_ID, GST_INR FROM SHIPMENTS 
ORDER BY GST_INR ASC;  --0.2199--

-- TOTAL SHIPMENTS IN MONTH --
SELECT
MONTH(Dispatch_Date) AS Shipment_Month,
COUNT(*) AS Total_Shipments
FROM SHIPMENTS
GROUP BY MONTH(Dispatch_Date)
ORDER BY Shipment_Month;

-- SHIPMENTS GROUP BY PAYMENT METHODS --
SELECT Payment_Mode , COUNT(*) AS Total_Shipments FROM SHIPMENTS
GROUP BY Payment_Mode
ORDER BY Total_Shipments DESC;

-- TOTAL COD PAYMENTS --
CREATE VIEW TOTAL_COD_PAYMENT AS
SELECT COUNT(*) AS COD_Shipments FROM SHIPMENTS WHERE Payment_Mode = 'COD'; --1138 --
SELECT * FROM TOTAL_COD_PAYMENT;

--TOTAL AMOUNT COLLECTED FOR COD PAYMENTS --
SELECT SUM(Freight_Charge_INR) FROM SHIPMENTS WHERE Payment_Mode = 'COD';  -- ₹3244798--

-- WHICH PAYMENT METHOD GENERATED HIGHEST REVENUE --
SELECT Payment_Mode, SUM(Freight_Charge_INR) AS Total_Revenue
FROM SHIPMENTS
GROUP BY Payment_Mode
ORDER BY Total_Revenue DESC;

-- WHICH CUSTOMER GENERATED HIGHEST SHIPMENTS --
SELECT TOP 1
c.Customer_Name,
COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c
ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Name
ORDER BY Total_Shipments DESC;

--WHICH CUSTOMER GENERATED HIGHEST REVENUE --
SELECT TOP 1
c.Customer_Name,
SUM(s.Freight_Charge_INR) AS Total_Revenue
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c
ON s.Customer_ID=c.Customer_ID
GROUP BY c.Customer_Name
ORDER BY Total_Revenue DESC;

--HOW MANY CUTOMERS ARE PREMIUM CUSTOMERS --
SELECT CUSTOMER_TYPE , COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS WHERE Is_Premium = 'TRUE' 
GROUP BY Customer_Type;

--TOTAL CUSTOMERS OF EACH CUTOMER_TYPE --
SELECT
Customer_Type,
COUNT(*) AS Total_Customers
FROM CUSTOMERS
GROUP BY Customer_Type
ORDER BY Total_Customers DESC;


-- CUSTOMERS --
SELECT * FROM CUSTOMERS;

-- HOW MANY CUSTOMERS
CREATE VIEW TOTAL_CUSTOMERS AS
SELECT COUNT(Customer_ID) AS How_Many_Customers FROM CUSTOMERS;
SELECT * FROM TOTAL_CUSTOMERS;

-- HOW MANY CUSTOMER_TYPES
CREATE VIEW TOTAL_CUSTOMER_TYPES AS
SELECT COUNT(DISTINCT Customer_Type) AS How_Many_Customer_Types FROM CUSTOMERS;
SELECT * FROM TOTAL_CUSTOMER_TYPES;

-- WHICH CUTOMER MAKE HIGHEST REVENUE
CREATE VIEW HIGHEST_REVENUE_CUSTOMER AS
SELECT TOP 1 Customer_ID, Customer_Name, Total_Spend_INR AS Highest_Revenue
FROM Customers
WHERE Total_Spend_INR IS NOT NULL
ORDER BY Total_Spend_INR DESC;
SELECT * FROM HIGHEST_REVENUE_CUSTOMER;

-- WHICH CUSTOMERS MAKE LOWEST REVENUE
CREATE VIEW LOWEST_REVENUE_CUSTOMER AS
SELECT TOP 1 Customer_ID, Customer_Name, Total_Spend_INR AS Lowest_Revenue
FROM Customers WHERE Total_Spend_INR IS NOT NULL
ORDER BY Total_Spend_INR ASC;
SELECT * FROM LOWEST_REVENUE_CUSTOMER;

-- HOW MANY CUTOMERS ARE PREMIUM CUSTOMERS
CREATE VIEW TOTAL_PREMIUM_CUSTOMERS AS
SELECT COUNT(CUSTOMER_ID) AS PREMIUM_CUSTOMERS FROM CUSTOMERS WHERE Is_Premium = 'TRUE'
SELECT * FROM TOTAL_PREMIUM_CUSTOMERS;

-- HOW MANY CUSTOMERS ARE NOT PREMIUM CUTOMERS
CREATE VIEW NON_PREMIUM_CUSTOMERS AS
SELECT COUNT(CUSTOMER_ID) AS NON_PREMIUM_CUSTOMERS FROM CUSTOMERS WHERE Is_Premium = 'FALSE'
SELECT * FROM NON_PREMIUM_CUSTOMERS;

-- TOTAL SHIPMENTS PER CUTOMERS TYPE
SELECT c.Customer_Type, COUNT(s.Shipment_ID) AS Total_Shipments 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Type;

-- BY EACH TYPE HOW MANY CUSTOMERS ARE NOT PREMIUM CUSTOMERS
SELECT CUSTOMER_TYPE , COUNT(CUSTOMER_ID) AS NON_PREMIUM_CUSTOMERS FROM CUSTOMERS WHERE Is_Premium = 'FALSE'
GROUP BY Customer_Type;

-- WHOS CUTOMERS SHIPMENTS ARE DELAYED
SELECT DISTINCT c.Customer_ID, c.Customer_Name 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
WHERE s.Is_Delayed = 'TRUE';

-- HOW MANY ARE THE ACTIVE CUSTOMERS
SELECT COUNT(*) AS ACTIVE_CUSTOMERS FROM CUSTOMERS WHERE Total_Orders > 0;

-- WHICH PAYMENT METHOD PREFERED BY CUSTOMERS
SELECT Preferred_Payment, COUNT(Customer_ID) AS Preference_Count 
FROM CUSTOMERS
GROUP BY Preferred_Payment
ORDER BY Preference_Count DESC;

-- HOW MANY CUSTOMERS ORDER DELAYED AS PER CUSTOMER TYPE
SELECT C.Customer_Type, COUNT(*) AS Delayed_Orders FROM Customers C
INNER JOIN SHIPMENTS S ON C.Customer_ID = S.Customer_ID
WHERE S.Delivery_Status = 'Delayed'
GROUP BY C.Customer_Type;

-- HOW MANY CUSTOMERS HAVE RETURNED THERE SHIPMENTS
SELECT COUNT(DISTINCT Customer_ID) AS Customers_With_Returned_Shipments 
FROM SHIPMENTS 
WHERE Delivery_Status = 'Cancelled';

-- WHO ARE THE CUSTOMERS WHOSE ORDERS NOT DELIVERED
SELECT DISTINCT c.Customer_ID, c.Customer_Name 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
WHERE s.Delivery_Status = 'Lost';

-- WHICH CUSTOMERS HAVE HIGHEST SHIPMENTS
SELECT TOP 1 c.Customer_ID, c.Customer_Name, COUNT(s.Shipment_ID) AS Highest_Shipment_Count 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Highest_Shipment_Count DESC;

-- WHICH CUSTOMERS HAVE LOWEST SHIPMENTS
SELECT TOP 1 c.Customer_ID, c.Customer_Name, COUNT(s.Shipment_ID) AS Lowest_Shipment_Count 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Lowest_Shipment_Count ASC;

-- WHICH CUSTOMERS ACCEPTS PREPAID PAYMENTS
SELECT DISTINCT c.Customer_ID, c.Customer_Name 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
WHERE s.Payment_Mode = 'UPI' OR s.Payment_Mode = 'Prepaid' OR s.Payment_Mode = 'Credit' OR s.Payment_Mode = 'Wallet';

-- WHICH CUSTOMERS ACCEPTS COD SHIPMENTS
SELECT DISTINCT c.Customer_ID, c.Customer_Name 
FROM SHIPMENTS s
JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
WHERE s.Payment_Mode = 'COD';

-- WHICH CITY HAS MOST ORDERS
CREATE PROCEDURE TOP_CITY AS
SELECT TOP 1 City, SUM(Total_Orders) AS Most_Orders_City FROM CUSTOMERS GROUP BY City ORDER BY Most_Orders_City DESC;
EXEC TOP_CITY;

-- WHICH CITY HAVE LOWEST ORDERS
CREATE PROCEDURE LOW_ORDER_CITY AS
SELECT TOP 1 City, SUM(Total_Orders) AS Lowest_Orders_City FROM CUSTOMERS GROUP BY City ORDER BY Lowest_Orders_City ASC;
EXEC LOW_ORDER_CITY;

-- WHICH STATE HAVE MOST ORDERS
CREATE PROCEDURE HIGHEST_ORDER_STATE AS
SELECT TOP 1 State, SUM(Total_Orders) AS Most_Orders_State FROM CUSTOMERS GROUP BY State ORDER BY Most_Orders_State DESC;
EXEC HIGHEST_ORDER_STATE;

-- WHICH STATE HAS LOWEST ORDERS
SELECT TOP 1 State, SUM(Total_Orders) AS Lowest_Orders_State FROM CUSTOMERS GROUP BY State ORDER BY Lowest_Orders_State ASC;

-- WHICH IS THE MOST PREFERED PAYMENT METHODS BY CUSTOMERS
SELECT TOP 1 Preferred_Payment, COUNT(Customer_ID) AS Most_Preferred_Count 
FROM CUSTOMERS 
GROUP BY Preferred_Payment 
ORDER BY Most_Preferred_Count DESC;

-- HOW MANY CUSTOMERS HAVE GSTIN NUMBERS
CREATE VIEW GST_CUSTOMERS AS
SELECT COUNT(Customer_ID) AS Customers_With_GSTIN FROM CUSTOMERS WHERE GSTIN IS NOT NULL;

SELECT * FROM GST_CUSTOMERS;

-- TOTAL CREDIT LIMIT GIVEN BY ORGANISATION
CREATE VIEW TOTAL_CREDIT_LIMIT AS
SELECT SUM(Credit_Limit_INR) AS TOTAL_CREDIT_LIMIT FROM CUSTOMERS;

SELECT * FROM TOTAL_CREDIT_LIMIT;

-- AVERAGE CREDIT LIMIT GIVEN TO CUSTOMERS
CREATE VIEW AVG_CREDIT_LIMIT AS
SELECT AVG(Credit_Limit_INR) AS AVG_CREDIT_LIMIT FROM CUSTOMERS

SELECT * FROM AVG_CREDIT_LIMIT;

-- HIGHEST CREDIT LIMIT
CREATE VIEW MAX_CREDIT_LIMIT AS
SELECT MAX(Credit_Limit_INR) AS MAX_CREDIT_LIMIT FROM CUSTOMERS

SELECT * FROM MAX_CREDIT_LIMIT

-- LOWEST CREDIT LIMIT
CREATE VIEW MIN_CREDIT_LIMIT AS
SELECT MIN(Credit_Limit_INR) AS MIN_CREDIT_LIMIT FROM CUSTOMERS

SELECT * FROM MIN_CREDIT_LIMIT

-- WHO ARE THE CUTOMERS WHO DONT HAVE CREDIT LIMIT
CREATE VIEW NON_CREDIT_CUSTOMERS AS
SELECT Customer_ID, Customer_Name 
FROM CUSTOMERS 
WHERE Credit_Limit_INR  =  0;

SELECT * FROM NON_CREDIT_CUSTOMERS;

-- WHICH CUSTOMER TYPE HAS HIGHEST CREDIT LIMIT
SELECT TOP 1 Customer_Type, SUM(Credit_Limit_INR) AS Total_Credit 
FROM CUSTOMERS 
GROUP BY Customer_Type 
ORDER BY Total_Credit DESC;

-- WHICH CUSTOMER TYPE HAS LOWEST CREDIT LIMIT
SELECT TOP 1 Customer_Type, SUM(Credit_Limit_INR) AS Total_Credit 
FROM CUSTOMERS 
GROUP BY Customer_Type 
ORDER BY Total_Credit ASC;

-- WHO IS THE OLDEST CUSTOMER
SELECT TOP 1 Customer_ID, Customer_Name, Registration_Date AS Oldest_Date 
FROM CUSTOMERS 
ORDER BY Oldest_Date ASC;

-- WHO IS THE LATEST CUSTOMER
SELECT TOP 1 Customer_ID, Customer_Name, Registration_Date AS Newest_Date 
FROM CUSTOMERS 
ORDER BY Newest_Date ASC;

-- TOTAL ORDERS BY CUSTOMERS
CREATE VIEW TOTAL_ORDERS AS
SELECT SUM(Total_Orders) AS Total_Orders_By_All_Customers FROM CUSTOMERS;
SELECT * FROM TOTAL_ORDERS;

-- WHO ARE THE CUSTMERS WHO DONT HAVE PHONE NUMBER
SELECT Customer_ID, Customer_Name FROM CUSTOMERS WHERE Phone IS NULL; 

-- WHO ARE THE CUSTOMERS WHO DONT HAVE EMAIL
SELECT Customer_ID, Customer_Name FROM CUSTOMERS WHERE Email IS NULL ;

-- HOW MANY CUSTOMERS DONT HAVE ACCOUNT MANAGERS
SELECT COUNT(Customer_ID) AS Missing_Account_Managers FROM CUSTOMERS WHERE Account_Manager IS NULL OR Account_Manager = '';

-- HOW MANY CUSTOMERS ARE THERE WITH ONE MANAGER
SELECT Account_Manager, COUNT(Customer_ID) AS Total_Customers_Handled 
FROM CUSTOMERS 
WHERE Account_Manager IS NOT NULL AND Account_Manager <> ''
GROUP BY Account_Manager ORDER BY Account_Manager ASC;




-- VEHICLE --




-- Q1 - HOW MANY VEHICLES  
CREATE VIEW TOTAL_VEHICLES AS
SELECT COUNT(Vehicle_ID) AS How_Many_Vehicles FROM VEHICLES;  --6800 --
SELECT * FROM TOTAL_VEHICLES;

-- Q2 - HOW MANY VEHICLE_TYPES
CREATE VIEW VEHICLE_TYPES AS
SELECT COUNT(DISTINCT Vehicle_Type) AS How_Many_Vehicle_Types FROM VEHICLES;  --8 --
SELECT * FROM VEHICLE_TYPES;

-- Q3 - WHICH VEHICLE TYPE HAS HIGHEST MILEAGE
SELECT TOP 1 Vehicle_Type, AVG(Mileage_kmpl) AS Highest_Avg_Mileage 
FROM VEHICLES 
GROUP BY Vehicle_Type 
ORDER BY Highest_Avg_Mileage DESC;

-- Q4 - WHICH VEHICLE TYPE HAS LOWEST MILEAGE
SELECT TOP 1 Vehicle_Type, AVG(Mileage_kmpl) AS Lowest_Avg_Mileage 
FROM VEHICLES 
GROUP BY Vehicle_Type 
ORDER BY Lowest_Avg_Mileage ASC;

-- Q5 - HOW MANY VEHICLES ARE ACTIVE VEHICLES 
CREATE VIEW ACTIVE_VEHICLES AS
SELECT COUNT(Vehicle_ID) AS Active_Vehicles_Count FROM VEHICLES WHERE Is_Active = 'Active'  --3474-- 
SELECT * FROM ACTIVE_VEHICLES;

-- Q6 - AVG MILEAGE PER VEHICLE TYPE
SELECT Vehicle_Type, AVG(Mileage_kmpl) AS Total_Mileage_Sum FROM VEHICLES GROUP BY Vehicle_Type;

-- Q7 - HOW MANY VEHICLES ARE NOT ACTIVE VEHICLES
CREATE VIEW NON_ACTIVE_VEHICLES AS
SELECT COUNT(Vehicle_ID) AS Non_Active_Vehicles_Count FROM VEHICLES WHERE Is_Active = 'Inactive'; --3326--
SELECT * FROM NON_ACTIVE_VEHICLES;

-- Q8 - BY EACH TYPE HOW MANY VEHICLES ARE NOT ACTIVE VEHICLES
SELECT Vehicle_Type, COUNT(Vehicle_ID) AS Non_Active_Count 
FROM VEHICLES 
WHERE Is_Active = 'Inactive'
GROUP BY Vehicle_Type;

-- Q9 - HOW MANY VEHICLES ARE GPS ENABLED
CREATE VIEW GPS_VEHICLES AS
SELECT COUNT(Vehicle_ID) AS GPS_Enabled_Count FROM VEHICLES WHERE GPS_Enabled = 'Yes' ; --3422 --
SELECT * FROM GPS_VEHICLES;

-- Q10 - HOW MANY VEHICLES ARE NOT GPS ENABLED
CREATE VIEW NON_GPS_VEHICLES AS
SELECT COUNT(Vehicle_ID) AS GPS_Enabled_Count FROM VEHICLES WHERE GPS_Enabled = 'No' ; --3378--
SELECT * FROM NON_GPS_VEHICLES;

-- Q11 - WHICH FUEL TYPE PREFERED IN FLEET   
SELECT Fuel_Type, COUNT(Vehicle_ID) AS Fuel_Preference_Count 
FROM VEHICLES 
GROUP BY Fuel_Type 
ORDER BY Fuel_Preference_Count DESC;  -- ELECTRIC 1381 --

-- Q12 - WHICH MODEL HAS HIGHEST COUNT
SELECT TOP 1 Model, COUNT(Vehicle_ID) AS Highest_Model_Count FROM VEHICLES GROUP BY Model ORDER BY Highest_Model_Count DESC; --BHARAT BENZ 1415 : 507 --

-- Q13 - WHICH MODEL HAS LOWEST COUNT
SELECT TOP 1 Model, COUNT(Vehicle_ID) AS Lowest_Model_Count FROM VEHICLES GROUP BY Model ORDER BY Lowest_Model_Count ASC;

-- Q14 - WHICH STATE HAS MOST VEHICLES OPERATING
SELECT TOP 1 Operational_State, COUNT(Vehicle_ID) AS Most_Vehicles_State FROM VEHICLES GROUP BY Operational_State ORDER BY Most_Vehicles_State DESC;

-- Q15 - WHICH STATE HAS LOWEST VEHICLES OPERATING
SELECT TOP 1 Operational_State, COUNT(Vehicle_ID) AS Lowest_Vehicles_State FROM VEHICLES GROUP BY Operational_State ORDER BY Lowest_Vehicles_State ASC;

-- Q16 - TOTAL PAYLOAD CAPACITY GIVEN BY FLEET
SELECT SUM(Max_Payload_tons) AS Total_Network_Payload_Capacity FROM VEHICLES;

-- Q17 - AVERAGE PAYLOAD CAPACITY OF VEHICLES
SELECT AVG(Max_Payload_tons) AS Average_Payload_Capacity FROM VEHICLES;

-- Q18 - HIGHEST PAYLOAD CAPACITY
CREATE VIEW HIGHEST_PAYLOAD_CAPACITY AS
SELECT MAX(Max_Payload_tons) AS Highest_Payload_Capacity FROM VEHICLES;
SELECT * FROM HIGHEST_PAYLOAD_CAPACITY

-- Q19 - LOWEST PAYLOAD CAPACITY
CREATE VIEW LOWEST_PAYLOAD_CAPACITY AS
SELECT MIN(Max_Payload_tons) AS Lowest_Payload_Capacity FROM VEHICLES;
SELECT * FROM LOWEST_PAYLOAD_CAPACITY;

-- Q21 - WHICH VEHICLE TYPE HAS HIGHEST PAYLOAD CAPACITY
SELECT TOP 1 Vehicle_Type, SUM(Max_Payload_tons) AS Total_Payload 
FROM VEHICLES 
GROUP BY Vehicle_Type 
ORDER BY Total_Payload DESC;

-- Q22 - WHICH VEHICLE TYPE HAS LOWEST PAYLOAD CAPACITY
SELECT TOP 1 Vehicle_Type, SUM(Max_Payload_tons) AS Total_Payload 
FROM VEHICLES 
GROUP BY Vehicle_Type 
ORDER BY Total_Payload ASC;

-- Q23 - WHO IS THE OLDEST VEHICLE BY MANUFACTURE YEAR
CREATE VIEW OLDEST_VEHICLE AS
SELECT TOP 1 Vehicle_ID, Model, Manufacture_Year FROM VEHICLES WHERE Manufacture_Year IS NOT NULL ORDER BY Manufacture_Year ASC;
SELECT * FROM OLDEST_VEHICLE;

-- Q24 - WHO IS THE LATEST VEHICLE BY MANUFACTURE YEAR
CREATE VIEW LATEST_VEHICLE AS
SELECT TOP 1 Vehicle_ID, Model, Vehicle_Type, Manufacture_Year FROM VEHICLES WHERE Manufacture_Year IS NOT NULL ORDER BY Manufacture_Year DESC;
SELECT * FROM LATEST_VEHICLE;

-- Q25 - TOTAL DISTANCE RUN BY ALL VEHICLES
SELECT SUM(Odometer_km) AS Total_Distance_Traveled FROM VEHICLES;  --1,70,25,65,240--

-- Q26 - AVERAGE DISTANCE RUN BY VEHICLES
SELECT AVG(Odometer_km) AS Avg_Distance_Traveled FROM VEHICLES;  --2,50,377-

-- Q27 - VEHICLE WITH HIGHEST ODOMETER READING
SELECT TOP 1 Vehicle_ID, Model, Odometer_km FROM VEHICLES ORDER BY Odometer_km DESC;

-- Q28 - VEHICLE WITH LOWEST ODOMETER READING
SELECT TOP 1 Vehicle_ID, Model, Odometer_km FROM VEHICLES ORDER BY Odometer_km ASC;

-- Q29 - VEHICLES OVERDUE FOR MAINTENANCE SERVICE
SELECT Vehicle_ID, Model, Next_Service_Due FROM VEHICLES WHERE Next_Service_Due < GETDATE();

-- Q30 - VEHICLES WITH EXPIRED INSURANCE POLICY
SELECT Vehicle_ID, Model, Insurance_Expiry FROM VEHICLES WHERE Insurance_Expiry < GETDATE();

-- VEHICLE TYPES AND MODEL --
SELECT DISTINCT(VEHICLE_TYPE) FROM VEHICLES;

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = '2-Wheeler';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Pickup Van';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Light Commercial Vehicle';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Container Truck';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Medium Truck';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Tempo';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = '3-Wheeler';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Mini Truck';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Refrigerated Truck';

SELECT MODEL FROM VEHICLES WHERE Vehicle_Type = 'Heavy Truck';

SELECT DISTINCT(MODEL) FROM VEHICLES;


-- FIXING VEHICLE TYPE ERROR --

-- FIXING 2-WHEELER VEHICLES --
UPDATE VEHICLES 
SET Vehicle_Type = '2-Wheeler' 
WHERE Model = 'Hero Splendor' OR Model = 'Yulu Miracle';

-- FIXING 3-WHEELER VEHICLES & TEMPOS
UPDATE VEHICLES 
SET Vehicle_Type = '3-Wheeler' 
WHERE Model = 'TVS King' OR Model = 'Bajaj RE';

UPDATE VEHICLES 
SET Vehicle_Type = 'Tempo' 
WHERE Model = 'Piaggio Ape';

-- FIXING MINI TRUCKS & PICKUP VANS
UPDATE VEHICLES 
SET Vehicle_Type = 'Mini Truck' 
WHERE Model = 'Tata Ace' OR Model = 'Maruti Super Carry' OR Model = 'Euler HiLoad';

UPDATE VEHICLES 
SET Vehicle_Type = 'Pickup Van' 
WHERE Model = 'Mahindra Bolero Pickup' OR Model = 'Ashok Leyland DOST';

-- FIXING LIGHT COMMERCIAL VEHICLES & REFRIGERATED TRUCKS
UPDATE VEHICLES 
SET Vehicle_Type = 'Light Commercial Vehicle' 
WHERE Model = 'TATA 407' OR Model = 'Force Traveller';

-- FIXING MEDIUM, HEAVY, AND CONTAINER TRUCKS
UPDATE VEHICLES 
SET Vehicle_Type = 'Medium Truck' 
WHERE Model = 'Eicher Pro 2049' OR Model = 'BharatBenz 1415';

UPDATE VEHICLES 
SET Vehicle_Type = 'Heavy Truck' 
WHERE Model = 'Tata LPT 1613';

-- FIXING DONE  --




-- Warehouse --





SELECT * FROM WAREHOUSE;

-- HOW MANY WAREHOUSES
CREATE VIEW TOTAL_WAREHOUSES AS
SELECT COUNT(Warehouse_ID) AS Total_Warehouses FROM WAREHOUSE;
SELECT * FROM TOTAL_WAREHOUSES;

-- HOW MANY UNIQUE WAREHOUSE CITIES
SELECT COUNT(DISTINCT City) AS Unique_Cities FROM WAREHOUSE;

-- WHICH WAREHOUSE HAS THE HIGHEST CAPACITY TONS
CREATE VIEW HIGHEST_CAPACITY_WAREHOUSES AS
SELECT TOP 1 Warehouse_ID, Warehouse_Name, Capacity_tons FROM WAREHOUSE ORDER BY Capacity_tons DESC;
SELECT * FROM HIGHEST_CAPACITY_WAREHOUSES;

-- WHICH WAREHOUSE HAS THE LOWEST CAPACITY TONS
CREATE VIEW LOWEST_CAPACITY_WAREHOUSE AS 
SELECT TOP 1 Warehouse_ID, Warehouse_Name, Capacity_tons FROM WAREHOUSE ORDER BY Capacity_tons ASC;
SELECT * FROM LOWEST_CAPACITY_WAREHOUSE;

-- AVERAGE CAPACITY TONS GIVEN TO WAREHOUSES
SELECT AVG(Capacity_tons) AS Avg_Capacity_Tons FROM WAREHOUSE;

-- HOW MANY WAREHOUSES ARE HUGE CAPACITY WAREHOUSES
SELECT COUNT(Warehouse_ID) AS Mega_Warehouses_Count FROM WAREHOUSE WHERE Area_sqft >= 200000;

-- HOW MANY WAREHOUSES ARE LOW CAPACITY WAREHOUSES 
SELECT COUNT(Warehouse_ID) AS Small_Warehouses_Count FROM WAREHOUSE WHERE Area_sqft < 50000;

-- TOTAL OPERATIONAL STOCK PER WAREHOUSE TYPE
SELECT Warehouse_Type, SUM(Current_Stock_tons) AS Total_Stock_Held FROM WAREHOUSE GROUP BY Warehouse_Type;

-- HOW MANY ARE THE ACTIVE WAREHOUSES
CREATE VIEW ACTIVE_WAREHOUSES AS
SELECT COUNT(Warehouse_ID) AS Active_Count FROM WAREHOUSE WHERE Operational_Status = 'Active';
SELECT * FROM ACTIVE_WAREHOUSES;

-- HOW MANY ARE THE NON ACTIVE WAREHOUSES
CREATE VIEW NON_ACTIVE_WAREHOUSES AS
SELECT COUNT(Warehouse_ID) AS Inactive_Count FROM WAREHOUSE WHERE Operational_Status = 'Inactive';
SELECT * FROM NON_ACTIVE_WAREHOUSES;

-- WHICH WAREHOUSE HAS THE HIGHEST MONTHLY INR COST
CREATE VIEW HIGHEST_MONTHLY_WAREHOUSE_COST AS
SELECT TOP 1 Warehouse_ID, Warehouse_Name, Monthly_Cost_INR FROM WAREHOUSE ORDER BY Monthly_Cost_INR DESC;
SELECT * FROM HIGHEST_MONTHLY_WAREHOUSE_COST;

-- HOW MANY WAREHOUSES ARE EQUIPPED WITH COLD STORAGE FACILITIES
SELECT Cold_Storage, COUNT(Warehouse_ID) AS Warehouse_Count FROM WAREHOUSE GROUP BY Cold_Storage;

-- HOW MANY WAREHOUSES IN EACH STATE
SELECT State, COUNT(Warehouse_ID) AS Warehouse_Count FROM WAREHOUSE GROUP BY State ORDER BY Warehouse_Count DESC;

-- WHICH CITY HAS MOST WAREHOUSES
SELECT TOP 1 City, COUNT(Warehouse_ID) AS City_Warehouse_Count FROM WAREHOUSE GROUP BY City ORDER BY City_Warehouse_Count DESC;

-- WHICH CITY HAS LOWEST WAREHOUSES
SELECT TOP 1 City, COUNT(Warehouse_ID) AS City_Warehouse_Count FROM WAREHOUSE GROUP BY City ORDER BY City_Warehouse_Count ASC;

-- WHICH STATE HAS THE HIGHEST STOCK RETENTION (TOTAL STOCK TONS)
SELECT TOP 1 State, SUM(Current_Stock_tons) AS Total_Stock FROM WAREHOUSE GROUP BY State ORDER BY Total_Stock DESC;

-- WHICH STATE HAS THE LOWEST STOCK RETENTION (TOTAL STOCK TONS)
SELECT TOP 1 State, SUM(Current_Stock_tons) AS Total_Stock FROM WAREHOUSE GROUP BY State ORDER BY Total_Stock ASC;

-- AVERAGE MONTHLY COST BY EACH STATE NETWORK
SELECT State, AVG(Monthly_Cost_INR) AS Avg_State_Cost FROM WAREHOUSE GROUP BY State;

-- WHICH WAREHOUSE TYPE CARRIES THE MAXIMUM CAPACITY OVERALL
SELECT TOP 1 Warehouse_Type, SUM(Capacity_tons) AS Total_Type_Capacity FROM WAREHOUSE GROUP BY Warehouse_Type ORDER BY Total_Type_Capacity DESC;

-- TOTAL ACTIVE WAREHOUSES ACROSS EACH STATE
SELECT State, COUNT(Warehouse_ID) AS Active_Count FROM WAREHOUSE WHERE Operational_Status = 'Active' GROUP BY State;

-- TOTAL MONTHLY RENTAL REVENUE GENERATED/SPENT ACROSS NETWORK
SELECT SUM(Monthly_Cost_INR) AS Grand_Total_Monthly_Cost FROM WAREHOUSE;

-- WHICH STATE RUNS THE HIGHEST MONTHLY LOGISTICS COST
SELECT TOP 1 State, SUM(Monthly_Cost_INR) AS Total_Cost FROM WAREHOUSE GROUP BY State ORDER BY Total_Cost DESC;

-- WHICH STATE RUNS THE LOWEST MONTHLY LOGISTICS COST
SELECT TOP 1 State, SUM(Monthly_Cost_INR) AS Total_Cost FROM WAREHOUSE GROUP BY State ORDER BY Total_Cost ASC;

-- AVERAGE RUNNING COST OF COLD STORAGE FACILITY SITES
SELECT AVG(Monthly_Cost_INR) AS Avg_Cold_Storage_Cost FROM WAREHOUSE WHERE Cold_Storage = 'Yes';

-- HIGHEST MONTHLY COST SPENT ON A STANDARD MOTHER WAREHOUSE
SELECT MAX(Monthly_Cost_INR) AS Max_Mother_WH_Cost FROM WAREHOUSE WHERE Warehouse_Type = 'Mother Warehouse';

-- LOWEST MONTHLY COST SPENT ON A LAST-MILE DARK STORE
SELECT MIN(Monthly_Cost_INR) AS Min_Dark_Store_Cost FROM WAREHOUSE WHERE Warehouse_Type = 'Dark Store';

-- WHICH WAREHOUSE TYPE RUNS THE HIGHEST RENTAL BILL
SELECT TOP 1 Warehouse_Type, SUM(Monthly_Cost_INR) AS Total_Type_Cost FROM WAREHOUSE GROUP BY Warehouse_Type ORDER BY Total_Type_Cost DESC;

-- WHICH WAREHOUSE TYPE RUNS THE CHEAPEST RENTAL BILL
SELECT TOP 1 Warehouse_Type, SUM(Monthly_Cost_INR) AS Total_Type_Cost FROM WAREHOUSE GROUP BY Warehouse_Type ORDER BY Total_Type_Cost ASC;

-- WHO IS THE OLDEST INFRASTRUCTURE SITE (MIN ESTABLISHED YEAR)
SELECT TOP 1 Warehouse_ID, Warehouse_Name, Established_Year FROM WAREHOUSE ORDER BY Established_Year ASC;

-- WHO IS THE LATEST INFRASTRUCTURE SITE CONSTRUCTED (MAX ESTABLISHED YEAR)
SELECT TOP 1 Warehouse_ID, Warehouse_Name, Established_Year FROM WAREHOUSE ORDER BY Established_Year DESC;

-- TOTAL VEHICLE CARRIERS LINKED PER WAREHOUSE OPERATIONAL CATEGORY
SELECT Warehouse_Type, COUNT(DISTINCT Carrier_ID) AS Carrier_Count FROM WAREHOUSE GROUP BY Warehouse_Type;

-- WHO ARE THE WAREHOUSES RUNNING WITHOUT PHONE NUMBERS DIRECTLY RECORDED
SELECT Warehouse_ID, Warehouse_Name FROM WAREHOUSE WHERE Manager_Phone IS NULL;

-- HOW MANY WAREHOUSES DON'T HAVE AN ASSIGNED MANAGER RECORDED
SELECT COUNT(Warehouse_ID) AS Missing_Managers_Count FROM WAREHOUSE WHERE Manager_Name IS NULL;





-- ROUTE --





-- HOW MANY TOTAL ROUTES ARE RECORDED
CREATE VIEW TOTAL_ROUTES AS
SELECT COUNT(Route_ID) AS Total_Routes FROM ROUTE;
SELECT * FROM TOTAL_ROUTES;

-- HOW MANY UNIQUE ORIGIN CITIES DO WE OPERATE FROM
SELECT COUNT(DISTINCT Origin_City) AS Unique_Origin_Cities FROM ROUTE;

-- WHICH ROUTE HAS THE LONGEST DISTANCE KM
CREATE VIEW LONGEST_ROUTE AS
SELECT TOP 1 Route_ID, Origin_City, Destination_City, Distance_km FROM ROUTE ORDER BY Distance_km DESC;
SELECT * FROM LONGEST_ROUTE;

-- WHICH ROUTE HAS THE SHORTEST DISTANCE KM
CREATE VIEW SHORTEST_ROUTE AS
SELECT TOP 1 Route_ID, Origin_City, Destination_City, Distance_km FROM ROUTE ORDER BY Distance_km ASC;
SELECT * FROM SHORTEST_ROUTE;

-- TOTAL DISTANCE CAPACITY 
SELECT SUM(Distance_km) AS Total_Network_Distance_KM FROM ROUTE;

-- AVERAGE DISTANCE OF ROUTES IN THE SYSTEM
SELECT AVG(Distance_km) AS Avg_Route_Distance_KM FROM ROUTE;

-- HOW MANY ROUTES INVOLVE LONG-DISTANCE TRANSIT (GREATER THAN 2500 KM)
CREATE VIEW LONG_DISTANCE_ROUTES AS
SELECT COUNT(Route_ID) AS Long_Distance_Count FROM ROUTE WHERE Distance_km >= 2500;
SELECT * FROM LONG_DISTANCE_ROUTES;

-- HOW MANY ROUTES INVOLVE SHORT-DISTANCE TRANSIT (LESS THAN 500 KM)
CREATE VIEW SHORT_DISTANCE_ROUTES AS
SELECT COUNT(Route_ID) AS Short_Distance_Count FROM ROUTE WHERE Distance_km < 500;
SELECT * FROM SHORT_DISTANCE_ROUTES;

-- TOTAL TOLL CHARGES COLLECTED/EXPECTED ACROSS THE FREIGHT SYSTEM
CREATE VIEW TOTAL_TOLL_CHARGES AS 
SELECT SUM(Toll_Charges_INR) AS Total_Toll_Charges_INR FROM ROUTE;
SELECT * FROM TOTAL_TOLL_CHARGES;

-- HOW MANY ACTIVE ROUTES ARE CURRENTLY RUNNING
CREATE VIEW ACTIVE_ROUTES AS
SELECT COUNT(Route_ID) AS Active_Routes FROM ROUTE WHERE Active = 'Yes';
SELECT * FROM ACTIVE_ROUTES;

-- HOW MANY INACTIVE ROUTES ARE CLOSED OR SUSPENDED
CREATE VIEW INACTIVE_ROUTES AS
SELECT COUNT(Route_ID) AS Inactive_Routes FROM ROUTE WHERE Active = 'No';
SELECT * FROM INACTIVE_ROUTES;

-- WHICH ROUTE HAS THE HIGHEST TOLL BILL ASSIGNED
SELECT TOP 1 Route_ID, Origin_City, Destination_City, Toll_Charges_INR FROM ROUTE ORDER BY Toll_Charges_INR DESC;

-- HOW MANY ROUTES RUN PURELY VIA HIGHWAY EXPRESSWAYS
CREATE VIEW TOTAL_HIGHWAY_ROUTES AS
SELECT Highway_Route, COUNT(Route_ID) AS Route_Count FROM ROUTE GROUP BY Highway_Route;
SELECT * FROM TOTAL_HIGHWAY_ROUTES;

-- HOW MANY FREIGHT ROUTES CORRIDORS EXIST PER ORIGIN STATE
SELECT Origin_State, COUNT(Route_ID) AS Routes_Dispatched FROM ROUTE GROUP BY Origin_State ORDER BY Routes_Dispatched DESC;

-- WHICH DESIGNATED ORIGIN CITY DISPATCHES THE MOST INDIVIDUAL COURIER CORRIDORS
SELECT TOP 1 Origin_City, COUNT(Route_ID) AS Dispatch_Volume FROM ROUTE GROUP BY Origin_City ORDER BY Dispatch_Volume DESC;

-- WHICH DESIGNATED ORIGIN CITY DISPATCHES THE FEWEST COURIER CORRIDORS
SELECT TOP 1 Origin_City, COUNT(Route_ID) AS Dispatch_Volume FROM ROUTE GROUP BY Origin_City ORDER BY Dispatch_Volume ASC;

-- WHICH DESTINATION STATE ACCEPTS THE HIGHEST TOTAL TOLL COSTS
SELECT TOP 1 Destination_State, SUM(Toll_Charges_INR) AS Total_State_Tolls FROM ROUTE GROUP BY Destination_State ORDER BY Total_State_Tolls DESC;

-- WHICH DESTINATION STATE ACCEPTS THE LOWEST TOTAL TOLL COSTS
SELECT TOP 1 Destination_State, SUM(Toll_Charges_INR) AS Total_State_Tolls FROM ROUTE GROUP BY Destination_State ORDER BY Total_State_Tolls ASC;

-- AVERAGE EXPEDITED SLA TIME GRANTED BY DESTINATION STATES
SELECT Destination_State, AVG(SLA_Days) AS Avg_SLA_Days FROM ROUTE GROUP BY Destination_State;

-- WHICH VEHICLE CATEGORY IS THE MOST PREFERRED OPTION FOR ROUTING
SELECT TOP 1 Preferred_Vehicle, COUNT(Route_ID) AS Vehicle_Preference_Count FROM ROUTE GROUP BY Preferred_Vehicle ORDER BY Vehicle_Preference_Count DESC;

-- TOTAL HIGHWAY COURIER TRACKS OPERATING WITH HIGH-RISK LEVELS
SELECT Risk_Level, COUNT(Route_ID) AS High_Risk_Count FROM ROUTE WHERE Risk_Level = 'High' GROUP BY Risk_Level;

-- TOTAL FUEL COSTS ACCUMULATED BY THE ENTIRE TRANSPORTATION NETWORK
SELECT SUM(Avg_Fuel_Cost_INR) AS Grand_Total_Fuel_Cost FROM ROUTE;

-- WHICH ORIGIN STATE GENERATES THE HIGHEST RUNNING FUEL FOOTPRINT
SELECT TOP 1 Origin_State, SUM(Avg_Fuel_Cost_INR) AS Total_State_Fuel_Cost FROM ROUTE GROUP BY Origin_State ORDER BY Total_State_Fuel_Cost DESC;

-- WHICH ORIGIN STATE GENERATES THE CHEAPEST RUNNING FUEL FOOTPRINT
SELECT TOP 1 Origin_State, SUM(Avg_Fuel_Cost_INR) AS Total_State_Fuel_Cost FROM ROUTE GROUP BY Origin_State ORDER BY Total_State_Fuel_Cost ASC;

-- HOW MANY ROUTES GENERATED REASONABLE TRANSIT JOURNEYS (VALID DAYS > 0)
SELECT COUNT(Route_ID) AS Valid_Transit_Count FROM ROUTE WHERE Avg_Transit_Days > 0;

-- TOTAL TOLL COST DEVOTED EXCLUSIVELY TO 'HEAVY TRUCK' PASSAGES
SELECT SUM(Toll_Charges_INR) AS Heavy_Truck_Toll_Total FROM ROUTE WHERE Preferred_Vehicle = 'Heavy Truck';

-- AVERAGE TRANSIT DAYS REQUIRED BY 'CONTAINER TRUCK' SHIPPING RUNS
SELECT AVG(Avg_Transit_Days) AS Avg_Container_Days FROM ROUTE WHERE Preferred_Vehicle = 'Container Truck';

-- HIGHEST INDIVIDUAL FUEL BILL EXTRACTED ON A CORRIDOR
SELECT MAX(Avg_Fuel_Cost_INR) AS Peak_Fuel_Cost FROM ROUTE;

-- LOWEST INDIVIDUAL FUEL BILL EXTRACTED ON A CORRIDOR
SELECT MIN(Avg_Fuel_Cost_INR) AS Floor_Fuel_Cost FROM ROUTE;

-- WHO ARE THE COURIER LANES COMMITTED WITHOUT AN ACTIVE ROUTING CARRIER ASSIGNED
SELECT Route_ID, Origin_City, Destination_City FROM ROUTE WHERE Carrier_ID IS NULL;

-- WHICH RISK CLASSIFICATION LOGS THE HIGHEST RUNNING FUEL CHARGES
SELECT TOP 1 Risk_Level, SUM(Avg_Fuel_Cost_INR) AS Total_Risk_Fuel FROM ROUTE GROUP BY Risk_Level ORDER BY Total_Risk_Fuel DESC;

-- WHICH RISK CLASSIFICATION LOGS THE CHEAPEST RUNNING FUEL CHARGES
SELECT TOP 1 Risk_Level, SUM(Avg_Fuel_Cost_INR) AS Total_Risk_Fuel FROM ROUTE GROUP BY Risk_Level ORDER BY Total_Risk_Fuel ASC;

-- WHICH FREIGHT SECTOR RUNS UNDER THE TIGHTEST DELIVERY DEADLINE (MIN SLA DAYS)
SELECT TOP 1 Route_ID, Origin_City, Destination_City, SLA_Days FROM ROUTE ORDER BY SLA_Days ASC;

-- WHICH FREIGHT SECTOR RUNS UNDER THE LONGEST DELIVERY DEADLINE (MAX SLA DAYS)
SELECT TOP 1 Route_ID, Origin_City, Destination_City, SLA_Days FROM ROUTE ORDER BY SLA_Days DESC;

-- TOTAL UNIQUE CARRIER SUPPLIERS RUNNING THE TRUCKING FLEET PER RISK ZONE
SELECT Risk_Level, COUNT(DISTINCT Carrier_ID) AS Unique_Carriers FROM ROUTE GROUP BY Risk_Level;

-- WHO ARE THE TRACK CORRIDORS EXCEEDING A Standard 10-DAY EXPECTED TRANSIT WINDOW
SELECT Route_ID, Origin_City, Destination_City, Avg_Transit_Days FROM ROUTE WHERE Avg_Transit_Days > 10;

-- LIST OF HIGHWAY RUNS ASSIGNED DIRECTLY OVER 'CAR010' VENDOR PIPELINES
SELECT Route_ID, Origin_City, Destination_City, Distance_km FROM ROUTE WHERE Carrier_ID = 'CAR010';

-- HOW MANY DISTINCT DEPLOYMENT RISK CLASSIFICATIONS ARE ASSIGNED
SELECT COUNT(DISTINCT Risk_Level) AS Risk_Tiers_Count FROM ROUTE;

-- HOW MANY CORRIDORS BREACHED COURIER STANDARDS (TRANSIT DAYS EXCEEDS SLA TIMELINE)
SELECT COUNT(Route_ID) AS SLA_Breaches FROM ROUTE WHERE Avg_Transit_Days > SLA_Days;

-- HOW MANY ROUTING CHANNELS OPERATE WITH THE HIGHEST CRITICAL RISK STATUS RATING
SELECT COUNT(Route_ID) AS Critical_Risk_Routes_Count FROM ROUTE WHERE Risk_Level = 'Critical';




-- CARRIER --



SELECT * FROM CARRIER;

-- HOW MANY TOTAL CARRIERS ARE RECORDED
SELECT COUNT(Carrier_ID) AS Total_Carriers FROM CARRIER;

-- HOW MANY UNIQUE HEADQUARTER CITIES DO WE UTILIZE
SELECT COUNT(DISTINCT HQ_City) AS Unique_HQ_Cities FROM CARRIER;

-- WHICH CARRIER HAS THE LARGEST FLEET SIZE
SELECT TOP 1 Carrier_ID, Carrier_Name, Fleet_Size FROM CARRIER ORDER BY Fleet_Size DESC;

-- WHICH CARRIER HAS THE SMALLEST FLEET SIZE
SELECT TOP 1 Carrier_ID, Carrier_Name, Fleet_Size FROM CARRIER ORDER BY Fleet_Size ASC;

-- TOTAL FLEET SIZE ACTIVE ACROSS THE ENTIRE SUPPLY CHAIN
SELECT SUM(Fleet_Size) AS Total_Network_Fleet FROM CARRIER;

-- AVERAGE FLEET SIZE OF OUR TRANSPORTATION CARRIERS
SELECT AVG(Fleet_Size) AS Avg_Fleet_Size FROM CARRIER;

-- HOW MANY CARRIERS OPERATE MEGA FLEETS (GREATER THAN 15000 VEHICLES)
SELECT COUNT(Carrier_ID) AS Mega_Fleets_Count FROM CARRIER WHERE Fleet_Size >= 15000;

-- HOW MANY CARRIERS OPERATE LOCAL FLEETS (LESS THAN 2000 VEHICLES)
SELECT COUNT(Carrier_ID) AS Small_Fleets_Count FROM CARRIER WHERE Fleet_Size < 2000;

-- TOTAL ANNUAL REVENUE IN CR CONTROLED BY SERVICE TYPES
SELECT Service_Type, SUM(Annual_Revenue_Cr) AS Total_Revenue_Cr FROM CARRIER GROUP BY Service_Type;

-- HOW MANY CARRIERS ARE ISO CERTIFIED ORGANIZATIONS
SELECT COUNT(Carrier_ID) AS ISO_Certified_Count FROM CARRIER WHERE ISO_Certified = 'TRUE';

-- HOW MANY CARRIERS LACK OFFICIAL ISO CERTIFICATION
SELECT COUNT(Carrier_ID) AS Non_ISO_Count FROM CARRIER WHERE ISO_Certified = 'FALSE';

-- WHICH CARRIER HAS THE HIGHEST ANNUAL REVENUE GENERATION RECORDED
SELECT TOP 1 Carrier_ID, Carrier_Name, Annual_Revenue_Cr FROM CARRIER ORDER BY Annual_Revenue_Cr DESC;

-- HOW MANY CARRIERS POSSESS A SEPARATE AIR FREIGHT WING WITH OWNED AIRCRAFT
SELECT Owns_Aircraft, COUNT(Carrier_ID) AS Carrier_Count FROM CARRIER GROUP BY Owns_Aircraft;

-- HOW MANY CARRIERS ARE HEADQUARTERED IN EACH STATE
SELECT HQ_State, COUNT(Carrier_ID) AS Carrier_Count FROM CARRIER GROUP BY HQ_State ORDER BY Carrier_Count DESC;

-- WHICH HQ CITY HAS THE HIGHEST CONCENTRATION OF VENDORS
SELECT TOP 1 HQ_City, COUNT(Carrier_ID) AS City_Vendor_Volume FROM CARRIER GROUP BY HQ_City ORDER BY City_Vendor_Volume DESC;

-- WHICH HQ CITY HAS THE LOWEST CONCENTRATION OF VENDORS
SELECT TOP 1 HQ_City, COUNT(Carrier_ID) AS City_Vendor_Volume FROM CARRIER GROUP BY HQ_City ORDER BY City_Vendor_Volume ASC;

-- WHICH STATE VENDORS GENERATE THE MAXIMUM REVENUE
SELECT TOP 1 HQ_State, SUM(Annual_Revenue_Cr) AS Total_State_Revenue FROM CARRIER GROUP BY HQ_State ORDER BY Total_State_Revenue DESC;

-- WHICH STATE VENDORS GENERATE THE MINIMUM REVENUE
SELECT TOP 1 HQ_State, SUM(Annual_Revenue_Cr) AS Total_State_Revenue FROM CARRIER GROUP BY HQ_State ORDER BY Total_State_Revenue ASC;

-- AVERAGE ACTIVE PINCODES COVERED BY STATE NETWORKS
SELECT HQ_State, AVG(Active_Pincodes) AS Avg_Pincodes_Covered FROM CARRIER GROUP BY HQ_State;

-- WHICH SERVICE TYPE OPTION IS DEPLOYED THE MOST OVERALL BY CARRIERS
SELECT TOP 1 Service_Type, COUNT(Carrier_ID) AS Service_Type_Count FROM CARRIER GROUP BY Service_Type ORDER BY Service_Type_Count DESC;

-- TOTAL PAN-INDIA DISTRIBUTED PARTNERS WORKING WITH HIGH QUALITY RATINGS
SELECT Pan_India, COUNT(Carrier_ID) AS Carrier_Count FROM CARRIER WHERE Rating_5 >= 4.0 GROUP BY Pan_India;

-- TOTAL ACTIVE PINCODES SERVICED BY THE ENTIRE TRUCKING POOL
SELECT SUM(Active_Pincodes) AS Total_Network_Pincodes FROM CARRIER;

-- TOTAL FLEET DEPLOYED EXCLUSIVELY VIA 'EXPRESS' SERVICE OPERATIONS
SELECT SUM(Fleet_Size) AS Express_Fleet_Total FROM CARRIER WHERE Service_Type = 'Express';

-- AVERAGE CUSTOMER RATING RETURNED BY 'SAME DAY' DELIVERY SPECIALISTS
SELECT AVG(Rating_5) AS Avg_Same_Day_Rating FROM CARRIER WHERE Service_Type = 'Same Day';

-- HIGHEST INDIVIDUAL FLEET VOLUME MANAGED BY A SINGLE COMPANY
SELECT MAX(Fleet_Size) AS Peak_Fleet_Size FROM CARRIER;

-- LOWEST INDIVIDUAL FLEET VOLUME MANAGED BY A SINGLE COMPANY
SELECT MIN(Fleet_Size) AS Floor_Fleet_Size FROM CARRIER;

-- WHO ARE THE CARRIERS OPERATING COURIER NETWORKS WITHOUT PAN-INDIA RIGHTS
SELECT Carrier_ID, Carrier_Name, HQ_City FROM CARRIER WHERE Pan_India = 'no';

-- WHICH SERVICE TYPE SECTOR LOGS THE HIGHEST FLEET CAPACITY
SELECT TOP 1 Service_Type, SUM(Fleet_Size) AS Total_Fleet FROM CARRIER GROUP BY Service_Type ORDER BY Total_Fleet DESC;

-- WHICH SERVICE TYPE SECTOR LOGS THE LOWEST FLEET CAPACITY
SELECT TOP 1 Service_Type, SUM(Fleet_Size) AS Total_Fleet FROM CARRIER GROUP BY Service_Type ORDER BY Total_Fleet ASC;

-- WHO IS THE OLDEST VENDOR IN THE DIRECTORY (MIN FOUNDED YEAR)
SELECT TOP 1 Carrier_ID, Carrier_Name, Founded_Year FROM CARRIER ORDER BY Founded_Year ASC;

-- WHO IS THE NEWEST VENDOR IN THE DIRECTORY (MAX FOUNDED YEAR)
SELECT TOP 1 Carrier_ID, Carrier_Name, Founded_Year FROM CARRIER ORDER BY Founded_Year DESC;

-- TOTAL UNIQUE BRANDS OPERATING THE SHIPMENTS NETWORK WITH AN NPS SCORE OVER 40
SELECT Service_Type, COUNT(DISTINCT Carrier_Name) AS Satisfactory_Brands FROM CARRIER WHERE NPS_Score >= 40 GROUP BY Service_Type;

-- WHO ARE THE PARTNERS FAILING STANDARD CUSTOMER SERVICE RATING WINDOWS (RATING < 2.0)
SELECT Carrier_ID, Carrier_Name, Rating_5 FROM CARRIER WHERE Rating_5 < 2.0;



-- ANALYSIS USING JOIN --

-- Show shipment details with customer details.
SELECT s.Shipment_ID,s.Order_ID,s.Product_Category,s.Weight_kg,
s.Volume_m3,s.Freight_Charge_INR,s.Delivery_Status,
c.Customer_ID,c.Customer_Name,c.Customer_Type,c.City,c.State
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID;


-- Total shipments for each customer.
SELECT c.Customer_ID , c.Customer_Name,
COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Shipments DESC;


-- Total freight paid by each customer.
SELECT c.Customer_ID , c.Customer_Name,
SUM(s.Freight_Charge_INR) AS Total_Freight_Paid_INR
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Freight_Paid_INR DESC;


-- Total weight shipped by each customer.
SELECT c.Customer_ID , c.Customer_Name,
SUM(s.Weight_kg) AS Total_Weight_KG
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Weight_KG DESC;


-- Total volume shipped by each customer.
SELECT c.Customer_ID , c.Customer_Name,
SUM(s.Volume_m3) AS Total_Volume_M3
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Volume_M3 DESC;



-- Average freight paid by each customer.
SELECT c.Customer_ID , c.Customer_Name,
AVG(s.Freight_Charge_INR) AS Avg_Freight_Paid_INR
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Avg_Freight_Paid_INR DESC;


-- Average shipment weight by customer.
SELECT c.Customer_ID , c.Customer_Name,
AVG(s.Weight_kg) AS Avg_Shipment_Weight_KG
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Avg_Shipment_Weight_KG DESC;


-- Average shipment volume by customer.
SELECT c.Customer_ID , c.Customer_Name,
AVG(s.Volume_m3) AS Avg_Shipment_Volume_M3
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Avg_Shipment_Volume_M3 DESC;


-- Customer with maximum shipments.
SELECT TOP 1 c.Customer_ID,c.Customer_Name,
COUNT(s.Shipment_ID) AS Shipment_Count
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Shipment_Count DESC;


-- Customer with minimum shipments.
SELECT TOP 1 c.Customer_ID , c.Customer_Name,
COUNT(s.Shipment_ID) AS Shipment_Count
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Shipment_Count ASC;


-- Customer with highest freight charges.
SELECT TOP 1 c.Customer_ID , c.Customer_Name,
SUM(s.Freight_Charge_INR) AS Total_Freight_INR
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Freight_INR DESC;


-- Customer with lowest freight.
SELECT TOP 1 c.Customer_ID,c.Customer_Name,
SUM(s.Freight_Charge_INR) AS Total_Freight_INR
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Freight_INR ASC;


-- Customer type with highest shipments.
SELECT TOP 1 c.Customer_Type,
COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Type
ORDER BY Total_Shipments DESC;  --D2C--


-- Customer type with highest revenue.
SELECT TOP 1 c.Customer_Type,
SUM(s.Freight_Charge_INR) AS Total_Revenue_INR
FROM SHIPMENTS s
INNER JOIN CUSTOMERS c ON s.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Type
ORDER BY Total_Revenue_INR DESC

-- Total shipments by carrier (Bypassing broken Carrier_ID using Route_ID)
SELECT c.Carrier_Name, 
COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Total_Shipments DESC;


-- Total freight by carrier
SELECT c.Carrier_Name, SUM(s.Freight_Charge_INR) AS Total_Freight_INR
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Total_Freight_INR DESC;


-- Total weight by carrier
SELECT c.Carrier_Name, 
SUM(s.Weight_kg) AS Total_Weight_KG
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Total_Weight_KG DESC;


-- Total volume by carrier
SELECT c.Carrier_Name, 
SUM(s.Volume_m3) AS Total_Volume_M3
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Total_Volume_M3 DESC;


-- Average freight by carrier
SELECT c.Carrier_Name, 
AVG(s.Freight_Charge_INR) AS Avg_Freight_INR
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Avg_Freight_INR DESC;


-- Average weight by carrier
SELECT c.Carrier_Name, 
AVG(s.Weight_kg) AS Avg_Weight_KG
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Avg_Weight_KG DESC;


-- Average volume by carrier
SELECT c.Carrier_Name, 
AVG(s.Volume_m3) AS Avg_Volume_M3
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Avg_Volume_M3 DESC;


-- Carrier with maximum shipments
SELECT TOP 1 c.Carrier_Name, 
COUNT(s.Shipment_ID) AS Max_Shipments
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Max_Shipments DESC;


-- Carrier with minimum shipments
SELECT TOP 1 c.Carrier_Name, 
COUNT(s.Shipment_ID) AS Min_Shipments
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Min_Shipments ASC;


-- Carrier with highest freight
SELECT TOP 1 c.Carrier_Name, 
SUM(s.Freight_Charge_INR) AS Lowest_Freight_INR
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name 
ORDER BY Lowest_Freight_INR ASC;


-- Carrier Status Distribution Breakdown
SELECT c.Carrier_Name,s.Delivery_Status,
COUNT(s.Shipment_ID) AS Shipment_Count
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Carrier_Name, s.Delivery_Status
ORDER BY c.Carrier_Name, Shipment_Count DESC;


-- Carrier rating vs shipment count
SELECT c.Rating_5 AS Carrier_Rating, 
COUNT(s.Shipment_ID) AS Total_Shipments_Handled
FROM SHIPMENTS s
INNER JOIN ROUTE r ON s.Route_ID = r.Route_ID
INNER JOIN CARRIER c ON r.Carrier_ID = c.Carrier_ID
GROUP BY c.Rating_5 
ORDER BY Carrier_Rating DESC;

-- Show shipment with warehouse details
SELECT s.Shipment_ID, s.Order_ID, s.Product_Category, s.Freight_Charge_INR, s.Delivery_Status, w.Warehouse_ID, w.Warehouse_Name, w.Warehouse_Type, w.City
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID;

-- Total shipments by warehouse
SELECT w.Warehouse_Name, COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID
GROUP BY w.Warehouse_Name ORDER BY Total_Shipments DESC;

-- Total freight by warehouse
SELECT w.Warehouse_Name, SUM(s.Freight_Charge_INR) AS Total_Freight_INR
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID
GROUP BY w.Warehouse_Name ORDER BY Total_Freight_INR DESC;

-- Total weight by warehouse
SELECT w.Warehouse_Name, SUM(s.Weight_kg) AS Total_Weight_KG
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID
GROUP BY w.Warehouse_Name ORDER BY Total_Weight_KG DESC;

-- Average freight by warehouse
SELECT w.Warehouse_Name, AVG(s.Freight_Charge_INR) AS Avg_Freight_INR
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID
GROUP BY w.Warehouse_Name ORDER BY Avg_Freight_INR DESC;

-- Warehouse Type with maximum shipments
SELECT w.Warehouse_Type, COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN WAREHOUSE w ON s.Warehouse_ID = w.Warehouse_ID
GROUP BY w.Warehouse_Type ORDER BY Total_Shipments DESC;

-- Show shipment with vehicle details
SELECT s.Shipment_ID, s.Order_ID, s.Product_Category, s.Freight_Charge_INR, v.Vehicle_ID, v.Vehicle_Type, v.Model, v.Fuel_Type
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID;

-- Total shipments handled by vehicle type
SELECT v.Vehicle_Type, COUNT(s.Shipment_ID) AS Total_Shipments
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID
GROUP BY v.Vehicle_Type ORDER BY Total_Shipments DESC;

-- Total freight generated by vehicle model
SELECT v.Model, SUM(s.Freight_Charge_INR) AS Total_Freight_INR
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID
GROUP BY v.Model ORDER BY Total_Freight_INR DESC;

-- Total weight hauled by vehicle type
SELECT v.Vehicle_Type, SUM(s.Weight_kg) AS Total_Weight_KG
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID
GROUP BY v.Vehicle_Type ORDER BY Total_Weight_KG DESC;

-- Average cargo weight carried by vehicle model
SELECT v.Model, AVG(s.Weight_kg) AS Avg_Weight_KG
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID
GROUP BY v.Model ORDER BY Avg_Weight_KG DESC;

-- Vehicle fuel type utilization breakdown
SELECT v.Fuel_Type, COUNT(s.Shipment_ID) AS Total_Dispatches
FROM SHIPMENTS s
INNER JOIN VEHICLES v ON s.Vehicle_ID = v.Vehicle_ID
GROUP BY v.Fuel_Type ORDER BY Total_Dispatches DESC;


